version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: arturo
      POSTGRES_PASSWORD: arturo
      POSTGRES_DB: socialapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
